# Generated by Django 6.0.4 on 2026-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownloder', '0002_pdfreport_created_at_user_is_staff_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfreport',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
