# Generated by Django 6.0.4 on 2026-04-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownloder', '0003_pdfreport_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfreport',
            name='profile_picture',
        ),
    ]
