# Generated by Django 6.0.4 on 2026-04-22 06:19

import signature_pad.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownloder', '0004_remove_pdfreport_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreport',
            name='signature',
            field=signature_pad.fields.SignaturePadField(blank=True, null=True),
        ),
    ]
