# Generated by Django 6.0.4 on 2026-04-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownloder', '0005_alter_pdfreport_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreport',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
