# Generated by Django 6.0.4 on 2026-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfdownloder', '0009_article_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
